#!/usr/bin/env php
<?php
require __DIR__.'/vendor/autoload.php';


use agoalofalife\Commands\InstallCommand;
use Symfony\Component\Console\Application;

$application = new Application();
$application->add(new InstallCommand());
$application->run();